version: "3.8"

services:
  app:
    build: .
    container_name: insignia-python-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: flask --app src/app.py run

volumes:
  mongo-data:
